Repository SrijanShovit/carbonops-v2, pull requests merged in 2023-05, with the labels that each got.

#7 [Bug]: Oauth logo added
  README.md
Labels: GSSOC

#10 Update README.md
  README.md
Labels: GSSOC

#23 Created LICENSE
  LICENSE
Labels: good first issue, GSSOC

#29 feat : Created fully responsive homepage
  app/colors.css
  app/globals.css
  app/home.js
  app/layout.js
  app/page.js
  components/Footer.js
  components/Navbar.js
  components/homepage/Graph.js
  components/homepage/Hero.js
  components/homepage/Organizations.js
  components/homepage/Services.js
  package-lock.json
  package.json
  public/images/Carbonops.png
  public/images/footer/Facebook.png
  public/images/footer/Google.png
  public/images/footer/Twitter.png
  public/images/homepage/Hero.png
  public/images/homepage/Interview.png
  public/images/homepage/documents.png
  public/images/homepage/profile.png
  public/images/homepage/service-1.png
Labels: GSSOC, UI

#31 Added 'Tailwind CSS' logo README
  README.md
Labels: documentation, GSSOC

#35 feat: Created signup page for individuals and organizations
  app/globals.css
  app/layout.js
  app/page.js
  app/signup/individual/page.js
  app/signup/layout.js
  app/signup/organization/page.js
  app/signup/page.js
  components/Footer.js
  components/Navbar.js
  components/homepage/Graph.js
  components/homepage/Hero.js
  components/homepage/Organizations.js
  components/homepage/Services.js
  components/signup/Card.js
  public/icons/cake.png
  public/icons/contact.png
  public/icons/email.png
  public/icons/lock.png
  public/icons/phone.png
  public/images/homepage/graph.png
  public/images/signup/individual.png
  public/images/signup/organizations.png
  public/images/signup/welcome_img.png
Labels: GSSOC, UI

#40 Fixed login and signUp bug for Mobile Navmenu
  components/Navbar.js
Labels: bug, GSSOC

#41 Added Scroll to Top
  app/page.js
  components/GoToTop.js
  package-lock.json
  package.json
Labels: enhancement, GSSOC
