Repository SrijanShovit/carbonops-v2, pull requests merged in 2023-07, with the labels that each got.

#102 Calculation of Carbon Footprint added
  app/calculate/page.js
  app/page.js
  components/homepage/Hero.js
  package-lock.json
  package.json
  tailwind.config.js
Labels: gssoc23, level2

#123 footer section full width
  app/page.js
Labels: gssoc23, level1

#158 Improvement: Optimize image paths for better maintainability
  app/calculate/page.js
  app/login/page.js
  app/signup/individual/page.js
  app/signup/organization/page.js
  app/signup/page.js
  components/Aboutus/Banner.js
  components/Aboutus/Navbar.js
  components/Aboutus/TeamCard.js
  components/Footer.js
  components/Navbar.js
  components/homepage/Graph.js
  components/homepage/Hero.js
  components/homepage/Organizations.js
  components/homepage/Services.js
  yarn.lock
Labels: gssoc23, level1

#151 placards in About us section improved
  components/Aboutus/Navbar.js
  components/Aboutus/TeamCard.js
  package-lock.json
  yarn.lock
Labels: gssoc23, level2

#161 Hero img doesn't overlap navbar now
  app/globals.css
Labels: gssoc23, level1

#193 adding src directory for improved code organization
  jsconfig.json
  src/app/ProviderWrapper.jsx
  src/app/aboutus/page.js
  src/app/api/auth/[...nextauth]/route.js
  src/app/calculate/page.js
  src/app/colors.css
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.js
  src/app/login/page.js
  src/app/page.js
  src/app/signup/individual/page.js
  src/app/signup/layout.js
  src/app/signup/organization/page.js
  src/app/signup/page.js
  src/components/Aboutus/Banner.js
  src/components/Aboutus/Contact.js
  src/components/Aboutus/Navbar.js
  src/components/Aboutus/Team.js
  src/components/Aboutus/TeamCard.js
  src/components/Footer.js
  src/components/GoToTop.js
  src/components/Navbar.js
  src/components/homepage/Graph.js
  src/components/homepage/Hero.js
  src/components/homepage/Organizations.js
  src/components/homepage/Services.js
  src/components/signup/Card.js
  tailwind.config.js
Labels: gssoc23, level3

#153 added individual dashboard ui
  .eslintrc.json
  package-lock.json
  package.json
  public/fonts/IBMPlexMono-SemiBold.woff2
  public/icons/plus.png
  public/images/individual/footprint.png
  public/images/individual/profileimage.png
  public/images/individual/visitorinfo.png
  src/app/login/page.js
  src/app/myprofile/page.js
  src/components/Individual/actions.js
  src/components/Individual/chart.js
  src/components/Individual/edit.js
  src/components/Individual/nav.js
  src/components/Individual/profilecard.js
  src/components/Individual/stats.js
  yarn.lock
Labels: gssoc23, level2

#171 feat: Developed products page UI
  app/products/page.js
  components/products/Navbar.jsx
  public/images/products/grayStar.png
  public/images/products/yellowStar.png
Labels: gssoc23, level2

#183 update score when option is changed
  package.json
  src/app/calculate/page.js
Labels: gssoc23, level2

#172 navbar improvement
  package-lock.json
  src/components/Navbar.js
  yarn.lock
Labels: gssoc23, level1

#213 feat: developed feeds page UI
  src/app/feeds/page.js
Labels: gssoc23, level2

#198 Applied the dark theme
  package-lock.json
  src/app/globals.css
  src/app/layout.js
  src/components/Aboutus/Navbar.js
  src/components/Navbar.js
  yarn.lock
Labels: gssoc23, level2

#194 Signup login backend
  .env.example
  .gitignore
  backend/app.js
  backend/config/DBMethods.js
  backend/config/db.config.js
  backend/controllers/userOperations.js
  backend/models/allUsers.js
  backend/package-lock.json
  backend/package.json
  backend/routers/example.routes.js
  package-lock.json
  package.json
  src/app/URL.js
  src/app/api/auth/[...nextauth]/route.js
  src/app/login/page.js
  src/app/signup/individual/page.js
  yarn.lock
Labels: gssoc23, level3

#204 Spelling corrected
  README.md
Labels: gssoc23, level1
