Repository SrijanShovit/carbonops-v2, pull requests merged in 2023-06, with the labels that each got.

#60 #57 Greeting bot added
  .github/workflows/greetings.yml
Labels: enhancement, GSSOC

#56 fix: Refractored the README.md and added animated thank you gif
  README.md
  public/gif/thankyou.gif
Labels: documentation, enhancement, gssoc23, level1

#48 Added Contributing Guidelines
  CONTRIBUTING.md
  README.md
Labels: documentation, gssoc23, level1

#64 feat: Created carbon footprint calculator UI
  app/calculate/page.js
Labels: gssoc23, level2

#69 placeholder issue is resolve
  app/login/page.js
Labels: gssoc23, level1

#71 Scrollbar styling changed
  app/colors.css
  app/globals.css
  package-lock.json
  package.json
Labels: gssoc23, level1

#66 #58 depandabot added
  .github/dependabot.yml
Labels: gssoc23, level2

#76 feat: created ER diagram
  ER_Diagram_Carbonops.png
  README.md
Labels: gssoc23, level2

#75 added radio buttons on the login page for choosing a category
  app/login/page.js
Labels: gssoc23, level1

#95 Addition in navbar
  components/Navbar.js
Labels: gssoc23, level2

#101 feat: password visibility toggle button added
  app/login/page.js
  app/signup/individual/page.js
  app/signup/organization/page.js
Labels: gssoc23, level1

#88 UI improvement About us done
  app/aboutus/page.js
  components/Aboutus/Banner.js
  components/Aboutus/Contact.js
  components/Aboutus/Navbar.js
  components/Aboutus/Team.js
  components/Aboutus/TeamCard.js
Labels: gssoc23, level2

#116 MVC Folder Structure & Schema
  backend/.env
  backend/.gitignore
  backend/app.js
  backend/config/db.config.js
  backend/controllers/example.controllers.js
  backend/models/events.model.js
  backend/models/events_registered.js
  backend/models/individual_profle_completions.model.js
  backend/models/organization_profile_completion.model.js
  backend/models/products.model.js
  backend/models/score.model.js
  backend/package-lock.json
  backend/package.json
  backend/routers/example.routes.js
  package-lock.json
  package.json
Labels: gssoc23, level3

#107 Integrated Github api to fetch contributors
  components/Aboutus/Team.js
  components/Aboutus/TeamCard.js
  next.config.js
Labels: gssoc23, level2

#115 adding workflow
  .github/workflows/preview.yaml
  package.json
  yarn.lock
Labels: gssoc23, level1

#72 added the animation on hero sec
  app/globals.css
  app/layout.js
  components/homepage/Hero.js
  package-lock.json
  package.json
Labels: gssoc23, level1

#109 feat: add login and logout using google auth
  .env.example
  app/ProviderWrapper.jsx
  app/api/auth/[...nextauth]/route.js
  app/layout.js
  app/login/page.js
  components/Navbar.js
  package.json
Labels: backend, api, gssoc23, level3
